# Generated by Django 5.2.7 on 2025-11-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder_files',
            name='is_backup',
            field=models.BooleanField(default=False),
        ),
    ]
